#include <zlib.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <fstream>
#include <iostream>
#include <sstream>
#include <cstring>
#include <fcntl.h>
//<ID> 890
//<Prompt> []
/*<Combination>: [
*/
//<score> 0, nr_unique_branch: 0
//<Quality> {"density":0,"unique_branches":{},"library_calls":[],"critical_calls":[],"visited":0}
/**/
int test_zlib_api_sequence() {
    // step 1: Declarations and initialization (prepare source and deflate stream)
    const char payload[] = "zlib api sequence payload for deflate and inflate";
    const uLong payload_len = (uLong)(sizeof(payload) - 1);
    const Bytef *src_buf = (const Bytef *)payload;
    uLong bound = compressBound((uLong)payload_len);
    Bytef *comp_buf = new Bytef[(bound ? bound : 1)];
    uLongf comp_buf_size = (uLongf)bound;
    z_stream dstrm;
    memset(&dstrm, 0, (size_t)sizeof(z_stream));
    int rc_deflate_init = deflateInit_(&dstrm, 6, zlibVersion(), (int)sizeof(z_stream));
    gz_header head;
    memset(&head, 0, (size_t)sizeof(gz_header));
    head.name = (Bytef *)"payload_name";
    head.name_max = (uInt)strlen((char *)head.name);
    head.comment = (Bytef *)"generated by test_zlib_api_sequence";
    head.comm_max = (uInt)strlen((char *)head.comment);
    int rc_set_header = deflateSetHeader(&dstrm, &head);
    dstrm.next_in = (Bytef *)src_buf;
    dstrm.avail_in = (uInt)(payload_len <= (uLong)~0u ? payload_len : (uLong)~0u);
    dstrm.next_out = comp_buf;
    dstrm.avail_out = (uInt)(comp_buf_size <= (uLong)~0u ? comp_buf_size : (uLong)~0u);
    int rc_deflate = deflate(&dstrm, 4); /* Z_FINISH == 4 */
    uLong compressed_bytes = dstrm.total_out;
    int rc_deflate_end = deflateEnd(&dstrm);

    // step 2: Write compressed bytes into a gzip file and add a formatted line with gzprintf
    gzFile gw = gzopen("test_zlib_api_sequence_tmp.gz", "wb");
    unsigned int write_len = (unsigned int)(compressed_bytes <= (uLong)~0u ? compressed_bytes : (uLong)~0u);
    int rc_gzwrite = gzwrite(gw, (voidpc)comp_buf, write_len);
    int rc_gzprintf = gzprintf(gw, "meta:compressed_bytes\n");
    int rc_gzflush = gzflush(gw, 0);
    int rc_gzclose_w = gzclose(gw);

    // step 3: Read back from the gzip file and perform inflate + mark on the compressed buffer
    gzFile gr = gzopen("test_zlib_api_sequence_tmp.gz", "rb");
    char *read_back = new char[256];
    memset(read_back, 0, 256);
    int rc_gzread = gzread(gr, (voidp)read_back, 255);
    int rc_gzclose_r = gzclose(gr);
    z_stream istrm;
    memset(&istrm, 0, (size_t)sizeof(z_stream));
    int rc_inflate_init = inflateInit_(&istrm, zlibVersion(), (int)sizeof(z_stream));
    istrm.next_in = comp_buf;
    istrm.avail_in = (uInt)(compressed_bytes <= (uLong)~0u ? compressed_bytes : (uLong)~0u);
    Bytef *unbuf = new Bytef[(payload_len ? payload_len : 1)];
    istrm.next_out = unbuf;
    istrm.avail_out = (uInt)(payload_len <= (uLong)~0u ? payload_len : (uLong)~0u);
    int rc_inflate = inflate(&istrm, 0);
    long mark = inflateMark(&istrm);
    int rc_inflate_end = inflateEnd(&istrm);

    // step 4: Cleanup, cast-away-unused warnings, and finalize
    delete [] comp_buf;
    delete [] unbuf;
    delete [] read_back;
    (void)rc_deflate_init;
    (void)rc_set_header;
    (void)rc_deflate;
    (void)rc_deflate_end;
    (void)compressed_bytes;
    (void)rc_gzwrite;
    (void)rc_gzprintf;
    (void)rc_gzflush;
    (void)rc_gzclose_w;
    (void)rc_gzread;
    (void)rc_gzclose_r;
    (void)rc_inflate_init;
    (void)rc_inflate;
    (void)mark;
    (void)rc_inflate_end;
    // API sequence test completed successfully
    return 66;
}