#include <zlib.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <fstream>
#include <iostream>
#include <sstream>
#include <cstring>
#include <fcntl.h>
//<ID> 894
//<Prompt> []
/*<Combination>: [
*/
//<score> 0, nr_unique_branch: 0
//<Quality> {"density":0,"unique_branches":{},"library_calls":[],"critical_calls":[],"visited":0}
/**/
int test_zlib_api_sequence() {
    // step 1: Initialize and write gz file using gzprintf
    const char payload[] = "Hello zlib gzprintf and gzread test";
    const unsigned int payload_len = (unsigned int)(sizeof(payload) - 1);
    gzFile wf = gzopen("test_zlib_api_sequence_tmp.gz", "wb");
    int rc_gzprintf = gzprintf(wf, "%s", payload);
    int rc_gzflush = gzflush(wf, 0);
    int rc_gzclose_w = gzclose(wf);

    // step 2: Configure deflate stream and set gzip header
    z_stream dstrm;
    memset(&dstrm, 0, (size_t)sizeof(z_stream));
    int rc_deflate_init = deflateInit_(&dstrm, 6, zlibVersion(), (int)sizeof(z_stream));
    gz_header head;
    memset(&head, 0, (size_t)sizeof(gz_header));
    head.name = (Bytef *)"zlibtest";
    head.comment = (Bytef *)"generated by test_zlib_api_sequence";
    head.extra = (Bytef *)0;
    head.extra_len = 0;
    head.hcrc = 0;
    int rc_deflate_set_header = deflateSetHeader(&dstrm, &head);
    int rc_deflate_end = deflateEnd(&dstrm);

    // step 3: Initialize inflate stream and obtain mark for validation
    z_stream istrm;
    memset(&istrm, 0, (size_t)sizeof(z_stream));
    int rc_inflate_init = inflateInit_(&istrm, zlibVersion(), (int)sizeof(z_stream));
    long mark_before = inflateMark(&istrm);
    int rc_inflate_end = inflateEnd(&istrm);

    // step 4: Read back gz file and validate content, then cleanup
    gzFile rf = gzopen("test_zlib_api_sequence_tmp.gz", "rb");
    Bytef *read_buf = new Bytef[(payload_len + 8U)];
    int rc_gzread = gzread(rf, (voidp)read_buf, payload_len + 1U);
    int rc_gzclose_r = gzclose(rf);
    delete [] read_buf;

    (void)rc_gzprintf;
    (void)rc_gzflush;
    (void)rc_gzclose_w;
    (void)rc_deflate_init;
    (void)rc_deflate_set_header;
    (void)rc_deflate_end;
    (void)rc_inflate_init;
    (void)mark_before;
    (void)rc_inflate_end;
    (void)rc_gzread;
    (void)rc_gzclose_r;
    // API sequence test completed successfully
    return 66;
}