#include <lcms2.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <vector>
#include <fstream>
#include <iostream>
#include <sstream>
#include <cstring>
#include <fcntl.h>
//<ID> 131
//<Prompt> []
/*<Combination>: [
*/
//<score> 0, nr_unique_branch: 0
//<Quality> {"density":0,"unique_branches":{},"library_calls":[],"critical_calls":[],"visited":0}
/**/
int test_lcms_api_sequence() {
    // step 1: Declarations
    cmsContext ctx = (cmsContext)NULL;
    cmsPipeline * lut = (cmsPipeline *)NULL;
    cmsUInt32Number inChannels = 3U;
    cmsUInt32Number outChannels = 3U;
    cmsHPROFILE hProfile = (cmsHPROFILE)NULL;
    cmsUInt8Number profileID[16] = {0};
    cmsHANDLE hIT8 = (cmsHANDLE)NULL;
    cmsInt32Number it8Result = 0;
    cmsNAMEDCOLORLIST * ncl = (cmsNAMEDCOLORLIST *)NULL;
    cmsUInt32Number lutInputChannels = 0;
    cmsUInt32Number lutStageCount = 0;

    // step 2: Setup
    lut = cmsPipelineAlloc(ctx, inChannels, outChannels);
    hProfile = cmsCreateLab4ProfileTHR(ctx, cmsD50_xyY());
    hIT8 = cmsIT8Alloc(ctx);
    ncl = cmsAllocNamedColorList(ctx, 1U, 3U, "pre", "suf");

    // step 3: Operate / Validate
    cmsGetHeaderProfileID(hProfile, profileID);
    lutInputChannels = cmsPipelineInputChannels(lut);
    lutStageCount = cmsPipelineStageCount(lut);
    it8Result = (cmsInt32Number) cmsIT8SetComment(hIT8, "Generated by test");
    cmsIT8SetPropertyDbl(hIT8, "Density", 1.23);
    cmsIT8SetDataFormat(hIT8, 0, "RGB");
    cmsIT8SetPropertyMulti(hIT8, "Key", "SubKey", "Val");
    cmsIT8SetSheetType(hIT8, "TYPE");

    // step 4: Cleanup
    cmsIT8Free(hIT8);
    cmsFreeNamedColorList(ncl);

    (void)ctx;
    (void)lut;
    (void)inChannels;
    (void)outChannels;
    (void)hProfile;
    (void)profileID;
    (void)hIT8;
    (void)it8Result;
    (void)ncl;
    (void)lutInputChannels;
    (void)lutStageCount;

    // API sequence test completed successfully
    return 66;
}